### PR TITLE
Use actual domain when resetting OPcache

### PR DESCRIPTION
**Pull request by m-vo**
The config key 'domain' will be used to build the URL; fallback to 'hostname' if not configured/truthy.

see #13

### CODE REVIEW

**Comment by richardhj** [comment]
IMHO you have to close the try-catch-clause before the `run()`.
Try to remove the try-catch-clause. AFAIK the exception will always be thrown when the config key is not set.

**Comment by m-vo** [comment]
I'm not really sure why we need to catch `ConfigurationException`, though. I put it in because the other parts of the code are doing so too. :smile: If I understand correctly `get()` already checks for a default value or if has been set and should not throw if not.

**Comment by m-vo** [comment]
Ah classic same second commenting.

**Comment by richardhj** [comment]
So it is safe to remove the try-catch-clause then? 😄

**Comment by m-vo** [comment]
Ok I see. One can either put a default value in...

```php
$domain = get('domain', get('hostname'));
// run
```

... or catch the exception:

```php
try {
    $domain = get('domain');
} catch(ConfigurationException $e) {
    $domain = get('hostname');
}
// run
```

Which one do you prefer?

**Comment by m-vo** [comment]
I used the first one - setting a fallback value (although a constant one, most often a string) is used throughout the default recipes.

**Comment by richardhj** [comment]
I guess I am the only one using this task. So I can ask nobody to review it 😆

**Comment by m-vo** [comment]
Thanks Richard!

**Pull request merged**
