### PR TITLE
Switch to richardhj/contao-backup-manager

### PR DESCRIPTION
**Pull request by richardhj**
I switched to https://github.com/richardhj/contao-backup-manager which is compatible with your backup_manager configuration.

WIP:
- [x] `add('shared_dirs', ['backups'])`
- [ ] Create a command (i.e. `contao:backups:purge`) that purges old backups after 2 weeks or so

### CODE REVIEW

**Comment by qzminski** [comment]
Why not keep the backup in the release folder? It would get automatically cleaned up during the old releases purging.

**Comment by richardhj** [comment]
> Why not keep the backup in the release folder? It would get automatically cleaned up during the old releases purging.

In case you are legally obligated to delete old backups, you have to purge these files.
When you keep the backups in the release folder, the backups might stay either for a too long or too short period (when having multiple deployments in a short time).

**Comment by richardhj** [comment]
For me, this is ready to merge.
@qzminski can you check if this results in incompatibilities with your projects since you were using `production` as the name?

**Comment by qzminski** [comment]
It should not collide, yet I have noticed that your bundle requires PHP 7.4 which would be a hard requirement for a big part of my projects. Can you introduce your solution as a separate command and perhaps `add('shared_dirs', ['backups'])` can go to the documentation instead being a part of every project? Or at least to the bootstrap file, so it can be adjusted if necessary.

**Comment by richardhj** [comment]
> I have noticed that your bundle requires PHP 7.4 which would be a hard requirement for a big part of my projects

The ^7.4 constraint was introduced in the latest minor (2.1.0) release, but composer should just use 2.0.0 in this case, no?

> Can you introduce your solution as a separate command and perhaps `add('shared_dirs', ['backups'])` can go to the documentation instead being a part of every project? Or at least to the bootstrap file, so it can be adjusted if necessary.

Moved to the bootstrap files. Is this ok?

**Comment by qzminski** [comment]
> The ^7.4 constraint was introduced in the latest minor (2.1.0) release, but composer should just use 2.0.0 in this case, no?

Ah okay, should be fine then.

> Moved to the bootstrap files. Is this ok?

Perfect for me 🙂

**Pull request merged**
